[workspace]
members = [
    ".",
    "flua-src",
    "flua-mlua-sys",
    "mlua-sys-shim", "mod-api", "factorio-mod-api-codegen", "factorio-mod-api-codegen-derive",
]
resolver = "2"

[patch.crates-io]
mlua-sys = { path = "mlua-sys-shim" }

[package]
name = "facts-and-oreos"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "facts-and-oreos"
path = "src/main.rs"

[lib]
name = "facts_and_oreos"
path = "src/lib.rs"

[build-dependencies]
factorio-mod-api-codegen = { path = "factorio-mod-api-codegen" }
serde_json = "1"

[dependencies]
factorio-mod-api-codegen = { path = "factorio-mod-api-codegen" }
flua-mlua-sys = { path = "flua-mlua-sys" }
clap = { version = "4.6.4", features = ["derive", "env"] }
hex = "0.4.3"
mlua = { version = "0.12", features = ["lua52"] }
mod-api = { path = "mod-api" }
regex = "1.13.1"
rootcause = "0.13.0"
semver = { version = "1.0.28", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha1 = "0.11.0"
toml = { version = "0.8", features = ["parse"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
