[workspace]
members = [
    ".",
    "flua-src",
    "flua-mlua-sys",
    "mlua-sys-shim", "mod-api",
]
resolver = "2"

[patch.crates-io]
mlua-sys = { path = "mlua-sys-shim" }

[package]
name = "facts-and-oreos"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "facts-and-oreos"
path = "src/main.rs"

[lib]
name = "facts_and_oreos"
path = "src/lib.rs"

[dependencies]
flua-mlua-sys = { path = "flua-mlua-sys" }
libc = "0.2.189"
mlua = { version = "0.12", features = ["lua52"] }
mod-api = { path = "mod-api" }
rootcause = "0.13.0"
semver = { version = "1.0.28", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha1_smol = "1.0.1"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
